name: Create Pull Request on new Uncertainty Input

on:
  workflow_dispatch: # Manual trigger
    inputs:
      payload:
        description: "JSON payload of new uncertainty"
        required: true
        default: '{}'

jobs: 
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: action/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npm run build

      - name: Run your script to update uncertainties.ts
        run: node  app/src/util/scripts/update-uncertainties.js "${{ github.event.inputs.payload }}"

      - name: Compile TypeScript again
        run: npm run build

      - name: Commit and push changes
        run: |
          git config --local user.name 'GitHub Action'
          git config --local user.email 'action@github.com'
          git add .
          git commit -m "Add new uncertainty"
          git push
      
      - name: Create Pull Request
        uses:  peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Add new uncertainty
          title: "Add new uncertainty"
          branch: "main"
          body: "Automated pull request to add new uncertainty"